---
title: "IOT Network Intrusion Detection Analysis"
subtitle: "INFO 526 - Fall 2024 - Project 01"
author: 
  - name: "ViZZards"
    affiliations:
      - name: "School of Information, University of Arizona"
description: "Analysis and Visualisation of various types of attacks in IOT network"
format:
   html:
    code-tools: true
    code-overflow: wrap
    embed-resources: true
editor: visual
execute:
  warning: false
  echo: false
---

## Abstract

This project focuses on analyzing and visualizing various types of network attacks in IoT (Internet of Things) environments using the RT-IoT 2022 dataset. The dataset captures detailed network traffic flow data, including both normal and malicious activity, across different IoT devices. The analysis aims to identify attack patterns through metrics like protocol usage, bandwidth, payload size, and flow characteristics. The study will address key questions about the distinctive network behaviors during different attacks, enabling future intrusion detection strategies. Ethical concerns are minimal as the dataset excludes sensitive organizational details. This work will provide insights into how network dimensions are impacted during attacks, contributing to enhanced cybersecurity in IoT systems.
